steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/custom-woodland-448200-m5/store-microservices/client-gateway",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west2-docker.pkg.dev/custom-woodland-448200-m5/store-microservices/client-gateway",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
